const actionTypes = {
  SET_USER_MODE: "SET_USER_MODE",
  SET_USER_IS_X: "SET_USER_IS_X",
  SET_SHOW_GAME: "SET_SHOW_GAME",
  RESET_BOARD_STATUS: "RESET_BOARD_STATUS",
  SET_STEP_NUMBER: "SET_STEP_NUMBER",
  SET_BOARD: "SET_BOARD",
  SET_WON_GAMES: "SET_WON_GAMES",
  SET_GAMES_PLAYED: "SET_GAMES_PLAYED",
};

export default actionTypes;
